DROP DATABASE IF EXISTS roadroutes_db;
-- CREATING DATABASE
CREATE DATABASE roadroutes_db;
-- CALLING THE DATABASE TO BE USED
USE roadroutes_db;
-- CREATING TABLE TO HOLD DATA FOR ROUTES THAT USER CREATES 
-- (THIS WILL BE DONE IN SEQUELIZE BUT THIS IS USED A REFERENCE)
CREATE TABLE routes (
    id INT NOT NULL AUTO_INCREMENT,
    userId VARCHAR(100) NOT NULL,
    routeState VARCHAR(50) NOT NULL,
    routeCity VARCHAR(50) NOT NULL,
    routeArea VARCHAR(20) NOT NULL,
    routeDistance INT NOT NULL,
    routeSteps VARCHAR (1000) NOT NULL,
    PRIMARY KEY (id), 
);

CREATE TABLE savedRoutes (
    id INT NOT NULL AUTO_INCREMENT,
    saved VARCHAR(200)
)